### ISSUE TITLE
pydantic error

### ISSUE THREAD

**Issue by fjgirante** [PBorocz/raindrop-io-py#5]
First of all, great work.
For a while it work fine, but now I'm, sometimes, receiving an error:
Exception has occurred: ValidationError
1 validation error for Raindrop
cache -> size
  ensure this value is greater than 0 (type=value_error.number.not_gt; limit_value=0)

in models.py module, while calling _search_paged in the line:
        return [cls(**item) for item in results["items"]]

it doesn't happen always - that's the strange thing, and seems to be related with some cache value and with pydantic.

Any clue on how to solve this?
Regards

**Comment by PBorocz** [comment]
Thank you! 
I haven't run into this but it sounds very much like it's associated with something specific to your particular collection (which is why I haven't run across it).

On first blush, not sure why the Raindrop API would be returning that something is in Cache but with a size of 0. I'm going to run this by the Raindrop developer and see if he has any ideas (his API doc is a bit "light"...).

A fix might be as simple as relaxing the pydantic type requirement on the cache size from `PositiveInt` to simply `Int`. Gimme a few days to see if anything better comes up.

**Comment by PBorocz** [comment]
I never heard back from Raindrop so I'm trying the "easy" route of simply allowing sizes of 0. 

Feel free to let me know if you still run into anything around this!
